<?php
/**
 * Created by PhpStorm.
 * User: SawHo
 * Date: 07.02.2019
 * Time: 0:32
 */

namespace app\components;

class MenuWidget extends \yii\base\Widget
{
    public $tpl;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if($this->tpl === null){
            $this->tpl = 'menu';
        }
        $this->tpl .= '.php';
    }

    public function run(){
        return $this->tpl;
    }
}